export const TYPES = {
  // Cocktail Types
  ADD_COCKTAIL: 'ADD_COCKTAIL',
  CLEAR_COCKTAIL: 'CLEAR_COCKTAIL',
  DELETE_COCKTAIL: 'DELETE_COCKTAIL',
  EDIT_COCKTAIL: 'EDIT_COCKTAIL',
  SET_COCKTAIL: 'SET_COCKTAIL',
  SET_COCKTAILS: 'SET_COCKTAILS',
  UPDATE_COCKTAILS: 'UPDATE_COCKTAILS',
  // Modal Types
  CLOSE_MODAL: 'CLOSE_MODAL',
  OPEN_MODAL: 'OPEN_MODAL',
};
